version: '3.9'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - DB_URL
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-linkby}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - node-network
    restart: unless-stopped

volumes:
  dbdata:
  postgres:

networks:
  node-network:
    driver: bridge
